DEST_DIR = /usr/lib/tc/

install:
	@sudo cp cloud_1_1/dist/* $(DEST_DIR)
	@sudo cp cloud_1_2/dist/* $(DEST_DIR)
	@sudo cp cloud_1_3/dist/* $(DEST_DIR)
	@sudo cp cloud_1_4/dist/* $(DEST_DIR)
	@sudo cp cloud_1_5/dist/* $(DEST_DIR)
	@sudo cp cloud_2_1/dist/* $(DEST_DIR)
	@sudo cp cloud_2_2/dist/* $(DEST_DIR)
	@sudo cp cloud_2_3/dist/* $(DEST_DIR)
	@sudo cp cloud_2_4/dist/* $(DEST_DIR)
	@sudo cp cloud_2_5/dist/* $(DEST_DIR)
	@sudo cp cloud_3_1/dist/* $(DEST_DIR)
	@sudo cp cloud_3_2/dist/* $(DEST_DIR)
	@sudo cp cloud_3_3/dist/* $(DEST_DIR)
	@sudo cp cloud_3_4/dist/* $(DEST_DIR)
	@sudo cp cloud_3_5/dist/* $(DEST_DIR)
	@sudo cp cloud_4_1/dist/* $(DEST_DIR)
	@sudo cp cloud_4_2/dist/* $(DEST_DIR)
	@sudo cp cloud_4_3/dist/* $(DEST_DIR)
	@sudo cp cloud_4_4/dist/* $(DEST_DIR)
	@sudo cp cloud_5_1/dist/* $(DEST_DIR)	

check:
	@cd $(DEST_DIR) && ls cloud_*.dist

clean:
	sudo rm $(DEST_DIR)/cloud_*.dist
